# Generated by Django 4.1.7 on 2023-05-04 14:49

from django.db import migrations, models

def create_data(apps, schema_editor):
	User = apps.get_model('usermanager', 'User')
	User.objects.create(nombre = "Jesús Prueba", username = "i02essej", password = "1234", email = "i02essej@uco.es").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(create_data),
    ]
