# Generated by Django 4.1.7 on 2023-06-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0.0)),
                ('totalWords', models.IntegerField(default=0)),
            ],
        ),
    ]
