# Generated by Django 4.1.7 on 2023-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
