# Generated by Django 4.1.7 on 2023-06-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_user_nombre_user_password_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
