# Generated by Django 4.1.7 on 2023-05-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default=(1, 'Spain', 'Upload'), max_length=5),
            preserve_default=False,
        ),
    ]
