# Generated by Django 4.1.7 on 2023-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_time_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='Wid',
            field=models.IntegerField(default=0),
        ),
    ]
