# Generated by Django 4.1.7 on 2023-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_country_name_word_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(max_length=4000, upload_to='uploads/'),
        ),
    ]
