# Generated by Django 4.1.7 on 2023-06-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_country_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='clue',
            new_name='Clue',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='Word',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='word',
            name='country',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default='nulo', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='country',
            name='Flag',
            field=models.CharField(default='nulo', max_length=4000),
        ),
        migrations.AddField(
            model_name='word',
            name='Country',
            field=models.ForeignKey(default='nulo', on_delete=django.db.models.deletion.CASCADE, to='words.country'),
            preserve_default=False,
        ),
    ]
